name: Test Module

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Validate module.json
      run: |
        # Check if module.json exists and is valid JSON
        if [ ! -f "module.json" ]; then
          echo "❌ module.json not found"
          exit 1
        fi
        
        # Validate JSON syntax
        if ! node -e "JSON.parse(require('fs').readFileSync('module.json', 'utf8'))"; then
          echo "❌ module.json contains invalid JSON"
          exit 1
        fi
        
        echo "✅ module.json is valid"
        
    - name: Validate required fields
      run: |
        # Check for required fields in module.json
        REQUIRED_FIELDS=("id" "title" "version" "compatibility")
        
        for field in "${REQUIRED_FIELDS[@]}"; do
          if ! node -e "
            const moduleJson = JSON.parse(require('fs').readFileSync('module.json', 'utf8'));
            if (!moduleJson.$field) {
              console.error('Missing required field: $field');
              process.exit(1);
            }
          "; then
            echo "❌ Missing required field: $field"
            exit 1
          fi
        done
        
        echo "✅ All required fields present"
        
    - name: Check JavaScript syntax
      run: |
        # Check if darkSun.js exists and has valid syntax
        if [ ! -f "darkSun.js" ]; then
          echo "❌ darkSun.js not found"
          exit 1
        fi
        
        # Basic syntax check
        if ! node -c darkSun.js; then
          echo "❌ darkSun.js contains syntax errors"
          exit 1
        fi
        
        echo "✅ darkSun.js syntax is valid"
        
    - name: Create test zip
      run: |
        # Test creating a zip file
        zip -r test-module.zip . -x "*.git*" "*.github*" "node_modules/*" "*.log" "*.tmp"
        
        # Check if zip was created successfully
        if [ ! -f "test-module.zip" ]; then
          echo "❌ Failed to create test zip file"
          exit 1
        fi
        
        echo "✅ Test zip created successfully"
        
    - name: Display module info
      run: |
        echo "📦 Module Information:"
        node -e "
          const moduleJson = JSON.parse(require('fs').readFileSync('module.json', 'utf8'));
          console.log('ID:', moduleJson.id);
          console.log('Title:', moduleJson.title);
          console.log('Version:', moduleJson.version);
          console.log('Compatibility:', JSON.stringify(moduleJson.compatibility));
        " 